import { Router } from "express";
import { oauthController } from "../controllers/oauth.controller";
import { authenticate } from "../middleware/authenticate";
import { z } from "zod";
import { validate } from "../middleware/validate";

const router = Router();
const createClientSchema = z.object({ body: z.object({ name: z.string().min(2).max(100), redirectUris: z.array(z.string().url()).min(1), scopes: z.array(z.string()).min(1), isConfidential: z.boolean().optional() }) });
const approveSchema = z.object({ body: z.object({ clientId: z.string().min(1), redirectUri: z.string().url(), scopes: z.string(), codeChallenge: z.string().min(43).max(128).optional(), codeChallengeMethod: z.literal("S256").optional(), state: z.string().max(2048).optional() }) });
router.post("/clients", authenticate, validate(createClientSchema), oauthController.createClient);
router.get("/clients", authenticate, oauthController.listClients);
router.delete("/clients/:clientId", authenticate, oauthController.revokeClient);
router.get("/consents", authenticate, oauthController.listConsents);
router.delete("/consents/:consentId", authenticate, oauthController.revokeConsent);
router.get("/authorize", oauthController.authorize);
router.post("/authorize/approve", authenticate, validate(approveSchema), oauthController.approve);
router.post("/token", oauthController.token);
router.get("/introspect", oauthController.introspect);
router.get("/userinfo", oauthController.userinfo);
export default router;
