import crypto from "crypto";
import { ConnectedProvider } from "@prisma/client";
import { prisma } from "../database/prisma";
import { AppError } from "../utils/AppError";
import { auditService } from "./audit.service";
import { env } from "../config/env";
const AUTH="https://www.instagram.com/oauth/authorize", TOKEN="https://api.instagram.com/oauth/access_token", GRAPH="https://graph.instagram.com";
const SCOPES=["instagram_business_basic"];
const key=()=>crypto.createHash("sha256").update(env.INSTAGRAM_TOKEN_ENCRYPTION_KEY||"").digest();
const enc=(v:string)=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",key(),iv),e=Buffer.concat([c.update(v,"utf8"),c.final()]);return [iv.toString("base64url"),c.getAuthTag().toString("base64url"),e.toString("base64url")].join(".")};
const dec=(v:string)=>{const [i,t,e]=v.split(".");if(!i||!t||!e)throw new AppError("Invalid encrypted Instagram credential",500,"INTERNAL_ERROR");const d=crypto.createDecipheriv("aes-256-gcm",key(),Buffer.from(i,"base64url"));d.setAuthTag(Buffer.from(t,"base64url"));return Buffer.concat([d.update(Buffer.from(e,"base64url")),d.final()]).toString("utf8")};
const hash=(v:string)=>crypto.createHash("sha256").update(v).digest("hex");
async function req(url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{Accept:"application/json",...(init.headers||{})}}),b:any=await r.json().catch(()=>({}));if(!r.ok)throw AppError.badRequest(b?.error?.message||"Instagram request failed","INSTAGRAM_REQUEST_FAILED",{status:r.status});return b}
export const instagramService={
async createAuthorizationUrl(userId:string){if(!env.INSTAGRAM_CLIENT_ID||!env.INSTAGRAM_CLIENT_SECRET||!env.INSTAGRAM_REDIRECT_URI||!env.INSTAGRAM_TOKEN_ENCRYPTION_KEY)throw new AppError("Instagram integration is not configured yet",503,"SERVICE_UNAVAILABLE");const state=crypto.randomBytes(32).toString("base64url");await prisma.oAuthIntegrationState.create({data:{provider:ConnectedProvider.INSTAGRAM,stateHash:hash(state),userId,verifierEnc:enc(state),expiresAt:new Date(Date.now()+600000)}});return AUTH+"?"+new URLSearchParams({client_id:env.INSTAGRAM_CLIENT_ID,redirect_uri:env.INSTAGRAM_REDIRECT_URI,response_type:"code",scope:SCOPES.join(","),state}).toString()},
async callback(q:{code?:string;state?:string;error?:string},ctx:{ipAddress?:string;userAgent?:string}){if(q.error)throw AppError.badRequest("Instagram authorization was cancelled","INSTAGRAM_ACCESS_DENIED");if(!q.code||!q.state)throw AppError.badRequest("Instagram authorization response was incomplete","INSTAGRAM_CALLBACK_INVALID");const s=await prisma.oAuthIntegrationState.findUnique({where:{stateHash:hash(q.state)}});if(!s||s.provider!==ConnectedProvider.INSTAGRAM||s.usedAt||s.expiresAt.getTime()<=Date.now())throw AppError.badRequest("Invalid or expired Instagram authorization state","INSTAGRAM_STATE_INVALID");const claim=await prisma.oAuthIntegrationState.updateMany({where:{id:s.id,usedAt:null},data:{usedAt:new Date()}});if(claim.count!==1)throw AppError.badRequest("Instagram authorization state has already been used","INSTAGRAM_STATE_REPLAYED");const form=new URLSearchParams({client_id:env.INSTAGRAM_CLIENT_ID!,client_secret:env.INSTAGRAM_CLIENT_SECRET!,grant_type:"authorization_code",redirect_uri:env.INSTAGRAM_REDIRECT_URI!,code:q.code});const tok=await req(TOKEN,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:form.toString()});if(!tok.access_token)throw AppError.badRequest("Instagram did not return an access token","INSTAGRAM_TOKEN_INVALID");const profile=await req(GRAPH+"/me?fields=id,username,account_type,media_count,profile_picture_url&access_token="+encodeURIComponent(tok.access_token));if(!profile.id)throw AppError.badRequest("Instagram did not return an account identifier","INSTAGRAM_PROFILE_INVALID");const existing=await prisma.connectedAccount.findUnique({where:{provider_providerAccountId:{provider:ConnectedProvider.INSTAGRAM,providerAccountId:String(profile.id)}}});if(existing&&existing.userId!==s.userId)throw AppError.conflict("This Instagram account is already connected to another MAX Account");await prisma.connectedAccount.upsert({where:{provider_providerAccountId:{provider:ConnectedProvider.INSTAGRAM,providerAccountId:String(profile.id)}},create:{userId:s.userId,provider:ConnectedProvider.INSTAGRAM,providerAccountId:String(profile.id),accessTokenEnc:enc(tok.access_token),refreshTokenEnc:null,scope:tok.permissions||SCOPES.join(","),tokenExpiresAt:null},update:{userId:s.userId,accessTokenEnc:enc(tok.access_token),scope:tok.permissions||SCOPES.join(","),tokenExpiresAt:null}});await auditService.record("CONNECTED_ACCOUNT_LINKED",{userId:s.userId,ipAddress:ctx.ipAddress,userAgent:ctx.userAgent,metadata:{provider:"INSTAGRAM",instagramAccountId:String(profile.id),username:profile.username}});return{status:"connected" as const}},
async accessToken(userId:string){const a=await prisma.connectedAccount.findFirst({where:{userId,provider:ConnectedProvider.INSTAGRAM}});if(!a?.accessTokenEnc)throw AppError.notFound("Instagram is not connected");return dec(a.accessTokenEnc)},
async me(userId:string){return req(GRAPH+"/me?fields=id,username,account_type,media_count,profile_picture_url&access_token="+encodeURIComponent(await this.accessToken(userId)))}
};